### ISSUE TITLE
[RFC] Add a separate section for weekly project and tooling reports

### ISSUE THREAD

**Issue by chshersh** [haskellweekly/haskellweekly#160]
I noticed recently that more and more projects in the Haskell ecosystem are becoming active. Their activity reached the point where they write weekly updates.

For example, the latest issue 350 contains **3 (!!!)** weekly updates from various ongoing Haskell projects and initiatives.

![Weekly updates](https://user-images.githubusercontent.com/4276606/212325889-6e83c71e-6228-4ba7-9601-eb7e48f1fbac.png)

I propose to add a separate section for weekly project and tooling reports that can contain all such weekly reports. Adding a separate section can make scanning the newsletter content for finding personally interested weekly updates easier.

This proposal is partially inspired by the _Project/Tooling Updates_ in [This Week in Rust](https://this-week-in-rust.org/blog/2023/01/04/this-week-in-rust-476/) newsletter that contains various updates on multiple tooling.

![image](https://user-images.githubusercontent.com/4276606/212326603-982eb783-c5eb-4451-9b5c-6a1f722a8a84.png)

Who knows, maybe GHC/Cabal/HLS/Hlint/Stan/etc. devs will join the mob with weekly updates on the status of the tooling 🙂

**Comment by chshersh** [comment]
Oh, and now there's another one:

* [IOG GHC Biweekly Update 2023-01-12](https://discourse.haskell.org/t/iog-ghc-biweekly-update-2023-01-12/5571)

**Comment by tfausak** [comment]
Thanks for the suggestion! 

I must admit that I'm a bit hesitant to add this. Add @ulysses4ever mentions, each new category introduces a new question you have to answer. Namely: "Does this content belong in this category?" For example I've become skeptical of the "Show & Tell" section because so often new releases of software are accompanied by blog posts, and it feels strange to relegate those to some other section. The intent of the section was to make a place for linking directly to GitHub repos, but that doesn't seem to happen enough to warrant a whole section for it. 

That being said, I'm not opposed either. I can see the value of having regularly repeating content in its own place, which would make focusing on novel content easier.

**Comment by tfausak** [comment]
One question I have about this potential section is: Should this only apply to weekly updates, or should it apply to any regular update? There are many updates that publish with different schedules:

- Weekly, for example: https://discourse.haskell.org/t/haskell-foundation-devops-weekly-update-2023-02-01/5713
- Bi-weekly, for example: https://discourse.haskell.org/t/ghc-devx-update-2023-01-26-iog-engineering/5676
- Bi-monthly, for example: https://discourse.haskell.org/t/haskell-foundation-december-and-january-2022-2023-update/5715

**Comment by chshersh** [comment]
I don't mind including not only weekly updates. The section could be named **Periodic updates**.

For example, the latest Haskell Weekly issue contains a link to the Monthly Hask Anything thread on `/r/haskell` and I'd be happy to see such updates in this section as well.

![image](https://user-images.githubusercontent.com/4276606/216772296-343c26ba-e1c7-4ed0-8a20-054be34a1ba8.png)

**Comment by tfausak** [comment]
I'm glad that you opened this issue, but I'd prefer to move in the other direction by removing or combining sections.
