### ISSUE TITLE
Featuring blog post on Bring your Haskell types to Reason.

### ISSUE THREAD

**Issue by felixminom** [haskellweekly/haskellweekly#26]
Hi! I want to suggest this article for the next issue:

[Bring your Haskell types to Reason](https://www.stackbuilders.com/news/bring-your-haskell-types-to-reason) by @dbalseiro

> One of the challenges that we face in web development is that we are often writing the backend and the frontend in different languages and type systems. To build reliable applications we need a way to connect both... We can build a bridge that helps us to traverse safely between the backend and the frontend. We can do that with a code generation tool that allows us to use the same types on both sides of the application.

The topic of this article was presented at [Compose Conference](http://www.composeconference.org/) New York in July 2019. [(video)](https://www.youtube.com/watch?v=BxUElNb-0Q0)

**Comment by tfausak** [comment]
Thanks for the suggestion! I would be happy to feature this in the upcoming issue of Haskell Weekly. If you'd like, you could open a pull request adding it to [issue 202](https://github.com/haskellweekly/haskellweekly/blob/haskellweekly/data/newsletter/issue-202.markdown). Otherwise I'll add it tomorrow evening when I put the issue together.

**Comment by tfausak** [comment]
Fixed by #27.
