### ISSUE TITLE
Add ids to headings for direct linking

### ISSUE THREAD

**Issue by ad-si** [haskellweekly/haskellweekly#280]
It would be cool if it were possible to link directly to the sections of a particular issue.
E.g. https://haskellweekly.news/issue/403.html#call-for-participation

For this to work the headings need to have an id like `<h2 id="call-for-participation">`.

**Comment by tfausak** [comment]
I would like to have this. 

Haskell Weekly uses the `cmark` package for parsing and rendering Markdown. For example, rendering Markdown as HTML happens here:

https://github.com/haskellweekly/haskellweekly/blob/8e224d0cd9747203a66439910b72869fce593e22/source/library/HW/Markdown.hs#L16-L17

Unfortunately I don't think `cmark` exposes anything that allows us to customize the rendering process. There's an open feature request for this: https://github.com/commonmark/cmark/issues/364

I can think of two ways to accomplish this:

- Switch to a Markdown processor that supports this directly or allows rendering to an actual HTML tree that we can traverse.
- Re-parse the generated HTML in order to walk over it and insert IDs where appropriate.

Note that Chrome supports this using a feature called "text fragments": https://web.dev/articles/text-fragments
